name: Deploy to Server

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ vars.APP_HOST }} > ~/.ssh/known_hosts

    - name: Create .env from GitHub secrets
      run: |
        echo BOT_TOKEN="${{ secrets.BOT_TOKEN }}" > .env

    - name: Transfer .env file to server
      run: scp .env ${{ vars.APP_HOST_USER }}@${{ vars.APP_HOST }}:${{ vars.APP_WORK_DIR }}/.env

    - name: connect and pull
      run: ssh ${{ vars.APP_HOST_USER }}@${{ vars.APP_HOST }} "cd ${{ vars.APP_WORK_DIR }} && git checkout ${{ vars.MAIN_BRANCH }} && docker-compose build && docker-compose down && docker-compose up -d && exit"

    - name: cleanup
      run: |
        rm -rf ~/.ssh
        rm .env